# Generated by Django 4.0.4 on 2022-07-18 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('test_plt', '0001_squashed_0019_alter_apirunlog_case_run_log_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectmember',
            name='role',
        ),
        migrations.AddField(
            model_name='projectmember',
            name='groups',
            field=models.ManyToManyField(related_name='member_belong_to', to='auth.group', verbose_name='角色（组）'),
        ),
        migrations.AlterField(
            model_name='apidef',
            name='protocol',
            field=models.CharField(choices=[('http', 'HTTP'), ('redis', 'Redis'), ('mysql', 'MySQL')], max_length=8, verbose_name='协议'),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.IntegerField(choices=[(1, 'web'), (2, 'App'), (3, '微服务')], verbose_name='产品类型'),
        ),
        migrations.AlterField(
            model_name='project',
            name='version',
            field=models.CharField(max_length=20, verbose_name='版本'),
        ),
    ]
