# Generated by Django 4.0.4 on 2022-07-20 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_plt', '0003_alter_queryparam_options_alter_project_members_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apidef',
            options={'permissions': [('run_apidef', '运行所选的接口')], 'verbose_name': '接口定义', 'verbose_name_plural': '接口定义'},
        ),
        migrations.AlterModelOptions(
            name='queryparam',
            options={'verbose_name': '查询参数', 'verbose_name_plural': '查询参数'},
        ),
    ]
