# Generated by Django 4.0.4 on 2022-07-24 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_plt', '0004_alter_apidef_options_alter_queryparam_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='case',
            options={'permissions': [('run_case', '运行所选用例')], 'verbose_name': '用例', 'verbose_name_plural': '用例'},
        ),
        migrations.AlterModelOptions(
            name='casesuite',
            options={'permissions': [('run_casesuite', '运行所选的用例套件')], 'verbose_name': '用例套件', 'verbose_name_plural': '用例套件'},
        ),
    ]
