# Generated by Django 4.0.4 on 2022-07-24 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_plt', '0008_caseapidef_mysql_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caseapidef',
            name='mysql_key',
            field=models.TextField(blank=True, null=True, verbose_name='Mysql 执行语句'),
        ),
    ]
