# Generated by Django 4.0.4 on 2022-07-24 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_plt', '0009_alter_caseapidef_mysql_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apirunlog',
            name='mysql_key',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Mysql 执行语句'),
        ),
    ]
