# Generated by Django 4.0.4 on 2022-07-24 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_plt', '0010_alter_apirunlog_mysql_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployenv',
            name='dingtalk_web_hook',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='钉钉群通知'),
        ),
        migrations.AddField(
            model_name='deployenv',
            name='dingtalk_web_hook_sign',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='钉钉加签'),
        ),
    ]
